title:  Lateral &co Studio
email: hello@lateralco.studio
description: >- # this means to ignore newlines until "baseurl:"
  Home on the web of Lateral &co Studio
baseurl: "/lateralco.studio" # the subpath of your site, e.g. /blog
domain: "https://lateralco.studio"
url: https://dopamine.github.io/lateralco.studio # the base hostname & protocol for your site, e.g. http://example.com
imgsrc: "https://pub-099e5bfd8c7f45b4bccf16f8a7ffa33f.r2.dev"
twitter_username: zita.freeburn
github_username:  dopamine

author:
  name: Zita
  url: https://lateralco.studio
  email: zita@lateralco.studio

nav_pages:
  - index.md
  - about.md

rss: "atom.xml"

collections:
  test:
    output: true

# Build settings
# theme: minima

sass:
  sass_dir: assets/_scss

plugins:
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:
 - setup-log.md
 - setup-ideas.md
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - CNAME
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/